language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true

script:
  - php -dphar.readonly=0 setup.php core:phar
  - curl https://phar.phpunit.de/phpunit-5.0.phar > phpunit.phar
  - php setup.php test
  - mkdir project
  - cd project
  - php ../setup.php skel:init

# deploy:
#   provider: releases
#   api_key: ""
#   file: "cf-2.0.phar"
#   skip_cleanup: true
#   on:
#     tags: true
