#!/usr/bin/env php
<?php
/**
 * Copyright (c) 2016 @CF_AUTHOR@
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Generated with CF @CF_VERSION@ on @DATE@
 **/

define("ROOT_DIR", dirname(__file__));
if (file_exists(ROOT_DIR . "/config/paths.php"))
	include_once(ROOT_DIR . "/config/paths.php");

if (file_exists(ROOT_DIR . "/vendor/autoload.php"))
	include_once(ROOT_DIR . "/vendor/autoload.php");

if (file_exists(ROOT_DIR . "/phpunit.phar"))
	include_once(ROOT_DIR . "/phpunit.phar");

if (!defined("CF_DIR"))
	die("Site not configured. To install dependencies, run\n\$ composer.phar install\n");

if (!file_exists(CF_DIR . "/setup.php"))
	die("Site not configured correctly. To install dependencies, run\n\$ composer.phar install\n");

include(CF_DIR . "/setup.php");
